<!DOCTYPE html>
<html lang="en">
<head>
<title>Interactive futures tutorial</title>
<style type="text/css" media="screen">
  div.editor { 
    width: 80em;
    height: 10em;
  }
  div.lesson {
    width: 82em;
    padding: 1em;
  }
  div.verify {
    display: none;
  }
  .passed {
    background-color: #ccffcc;
  }
  .failed {
    background-color: #ffcccc;
  }
  p {
    font-family: sans-serif;
  }
  .code > * {
    font-family: monospace;
  }
  td, th {
    text-align: left;
    padding-left: 0.5em; 
    padding-right: 0.5em;
    font-family: monospace;
  }
</style>
</head>
<body>

<h2>Intro</h2>
<p>
This is an interactive tutorial for futures. The code samples are intended to look and behave like Java but it's actually JavaScript.
"->" is automatically converted to "=>" so you can write lambdas like in Java.</p>

<p>Exceptions are similar to Java, but without anything fancy.</p>

<p>The <a href="https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletableFuture.html">CompletableFuture API</a> you can use here is a partial re-implementation in JavaScript. The functions you can use are listed below:
<p></p>
<p>Since Java 8:</p>
<ul class="code">
<li>var x = new CompletableFuture();
<li>var x = CompletableFuture.completedFuture(value);
<li> var newFuture = future.thenApply(value -> new_value);
<li> var newFuture = future.thenCompose(value -> new_future);
<li> var newFuture = future.exceptionally(exc -> new_value);
<li> var newFuture = future.handle((value, exc) -> new_value);
</ul>
<p>Since Java 9:</p>
<ul class="code">
<li>var x = CompletableFuture.failedFuture(exception);
</ul>
<p>Since Java 12:</p>
<ul class="code">
<li> var newFuture = future.exceptionallyCompose(exc -> new_future);
</ul>
</p>

<div id="lessons">
</div>
    
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>

<!-- https://cdnjs.com/libraries/ace -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.min.js" type="text/javascript" charset="utf-8"></script>
<script>
  var basePath = "https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/";
  ace.config.set("basePath", basePath);
  ace.config.set("themePath", basePath);

  class Exception {
    constructor(message) {
      this._message = message;
    }
    
    static wrap(exc) {
      if (exc == null) {
        return new Exception("Nullpointer");
      } else if (exc instanceof Exception) {
        return exc;
      } else {
        return new Exception(exc);
      }
    }
    
    getMessage() {
      return this.toString();
    }
    
    toString() {
      return this._message;
    }
  }
  
  function _assert(expr, msg) {
    if (!expr) {
      throw new Exception("Assertion failed: " + msg);
    }
  }
  
  function _assert_exc(exc) {
    _assert(exc instanceof Exception, "Expected an exception but found " + exc);
  }
  
  function _assert_future(future) {
    _assert(future instanceof CompletableFuture, "Expected an future but found " + future);
  }
  
  function _assert_result(result) {
    _assert(result instanceof Result, "Expected a result but found " + result);
  }
  
  function _assert_allowed(name) {
    if (_globalAllowed) {
      _assert(_globalAllowed.has(name), "Not allowed to call function: " + name);
    }
  }
  
  class Result {
    constructor(value, exception) {
      this._value = value;
      this._exception = exception;
    }
    
    static exception(exc) {
      return new Result(null, Exception.wrap(exc));
    }
    
    static value(value) {
      return new Result(value, null);
    }
    
    isException() {
      return this._exception != null;
    }

    isValue() {
      return this._exception == null;
    }
    
    equals(other) {
      return this._exception == other._exception && this._value == other._value;
    }
    
    toString() {
      if (this._exception != null) {
        return "Exception('" + this._exception.getMessage() + "')";
      }
      return "Value('" + this._value + "')";
    }
  }
  
  class CompletableFuture {
    constructor() {
      this._result = null;
      this._callbacks = [];
    }
    
    static completedFuture(value) {
      var newFuture = new CompletableFuture();
      newFuture.complete(value);
      return newFuture;
    }
    
    static failedFuture(exc) {
      _assert(_globalLanguageLevel >= 9, "Requires Java 9+");
      _assert_exc(exc);
      var newFuture = new CompletableFuture();
      newFuture.completeExceptionally(exc);
      return newFuture;
    }
    
    static _completedResult(result) {
      var f = new CompletableFuture();
      f._completeResult(result);
      return f;
    }
    
    // fun: Exception => Future
    exceptionallyCompose(fun) {
      _assert(_globalLanguageLevel >= 12, "Requires Java 12+");
      _assert_allowed("exceptionallyCompose");
      return this
        ._thenApply(x => CompletableFuture.completedFuture(x))
        ._exceptionally(fun)
        ._thenCompose(x => x);
    }
    
    // fun: (Value, Value) => Value
    thenCombine(other, fun) {
      _assert_allowed("thenCombine");
      return this._thenCompose(x => other._thenApply(y => fun(x, y)));
    }
    
    // fun: Exception => Value
    exceptionally(fun) {
      _assert_allowed("exceptionally");
      return this._exceptionally(fun);
    }
    
    _exceptionally(fun) {
      return this._handle((value, exc) => {
        if (exc != null) {
          return fun(exc);
        } else {
          return value;
        }
      });
    }

    // fun: Value => Value
    thenApply(fun) {
      _assert_allowed("thenApply");
      return this._thenApply(fun);
    }
    
    _thenApply(fun) {
      return this._handle((value, exc) => {
        if (exc != null) {
          throw exc;
        } else {
          return fun(value);
        }
      });
    }
    
    // fun: Value => Future
    thenCompose(fun) {
      _assert_allowed("thenCompose");
      return this._thenCompose(fun);
    }
    
    _thenCompose(fun) {
      return this._thenApply(fun)._dereference();
    }
    
    // fun: (Value, Exception) => Value
    handle(fun) {
      _assert_allowed("handle");
      return this._handle(fun);
    }
    
    _handle(fun) {
      return this._handleResult(result => {
        if (result.isValue()) {
          return Result.value(fun(result._value, null));
        } else {
          return Result.value(fun(null, result._exception));
        }
      });
    }
    
    // fun: Result => Result
    _handleResult(fun) {
      var newFuture = new CompletableFuture();
      this._addCallback(result => {
        try {
          var result2 = fun(result);
          _assert_result(result2);
          newFuture._completeResult(result2);
        } catch (err) {
          newFuture._completeResult(Result.exception(err));
        }
      });
      return newFuture;
    }
    
    _dereference() {
      var newFuture = new CompletableFuture();
      this._addCallback(result => {
        try {
          if (result.isValue()) {
            var future = result._value;
            _assert_future(future);
            future._addCallback(result2 => newFuture._completeResult(result2))
          } else {
            newFuture._completeResult(result);
          }
        } catch (err) {
          newFuture._completeResult(Result.exception(err));
        }
      });
      return newFuture;
    }

    // fun: Result => Void
    // fun may not throw errors
    _addCallback(fun) {
      if (this.isComplete()) {
        fun(this._result);
      } else {
        this._callbacks.push(fun);
      }
    }
        
    isComplete() {
      return this._result != null;
    }
    
    getResult() {
      if (!this.isComplete()) {
        throw "Future is not completed";
      }
      return this._result;
    }
    
    getValue() {
      var res = getResult();
      if (res.isException()) {
        throw "Future completed exceptionally";
      }
      return res._value;
    }
    
    complete(value) {
      this._completeResult(Result.value(value));
    }
    
    completeExceptionally(exc) {
      _assert_exc(exc);
      this._completeResult(Result.exception(exc));
    }
    
    _completeResult(result) {
      if (this._result == null) {
        this._result = result;
      }
      var callbacks = this._callbacks;
      this._callbacks = [];
      for (var callback of callbacks) {
        try {
          callback(result);
        } catch (err) {
          console.log("Unexpected error from callback: " + err.toString());
        }
      }
    }
    
    toString() {
      if (this._result != null) {
        return "CompleteFuture(" + this._result.toString() + ")";
      }
      return "IncompleteFuture";
    }
    
  }
  
  function compile(code, inputs) {
    var parameterList = inputs.join(', ');
    code = code.replaceAll("->", "=>");
    code = code.replaceAll("::", ".");
    code = "(" + parameterList + ") => { " + code + "}";
    return eval(code);
  }
  
  function evaluateFunction(code, inputs) {
    var inputFutures = [];
    for (var input of inputs) {
      inputFutures.push(new CompletableFuture());
    }
    var outputFuture = code(...inputFutures);

    // TODO: test various combinations of pre-completed inputs
    
    for (var inputFuture of inputFutures) {
      if (inputFuture.isComplete()) {
        throw "Unexpected modification of the input future";
      }
    }

    if (outputFuture == null) {
      throw "Output is null";
    }
    
    if (!(outputFuture instanceof CompletableFuture)) {
      throw "Return value has wrong type - expected CompletableFuture";
    }
    
    for (var i = 0; i < inputs.length; i++) {
      inputFutures[i]._completeResult(inputs[i]);
    }
    
    if (!outputFuture.isComplete()) {
      throw "Output future did not complete";
    }
    
    return outputFuture.getResult();
  }
  
  function generateTestCases(parameters, factories, random) {
    var testCases = [];
    generateTestCasesRec(testCases, parameters, factories, random, []);
    return testCases;
  }
  
  function generateTestCasesRec(testCases, parameters, factories, random, stack) {
    if (stack.length == parameters.length) {
      var inputs = [];
      for (var i = 0; i < parameters.length; i++) {
        var parameter = parameters[i];
        var factory = stack[i];
        inputs.push(factory(random, parameter));
      }
      testCases.push(inputs);
      return;
    }
    for (var factory of factories) {
      stack.push(factory);
      generateTestCasesRec(testCases, parameters, factories, random, stack);
      stack.pop();
    }
  }
  
  var randomNumbers = [];
  for (var i = 0; i < 10000; i++) {
    randomNumbers.push(Math.random());
  }
  
  class Random {
    constructor() {
      this._index = 0;
    }
    
    get() {
      var index = this._index;
      this._index++;
      if (this._index >= randomNumbers.length) {
        this._index = 0;
      }
      return randomNumbers[index];
    }
  }
  
  var inputFactories = [
    (random, name) => Result.value(name + Math.floor(random.get() * 10)),
    (random, name) => Result.exception(name + Math.floor(random.get() * 10)),
  ];
  
  function runTests(code, solution, parameters) {
    var random = new Random();
    var result;
    for (var i = 0; i < 10; i++) {
      result = [];
      var failed = false;
      var testCases = generateTestCases(parameters, inputFactories, random);
      for (var inputValues of testCases) {
        var testCase = {
          inputs: inputValues,
          actual: "",
          expected: "",
          error: "",
          failed: false
        }
        try {
          var actual = evaluateFunction(code, inputValues);
          var expected = evaluateFunction(solution, inputValues);
          testCase.actual = actual.toString();
          testCase.expected = expected.toString();
          testCase.failed = !(actual.equals(expected));
        } catch (err) {
          testCase.error = err.toString();
          testCase.failed = true;
        }
        result.push(testCase);
        if (testCase.failed) {
          failed = true;
        }
      }
      if (failed) {
        return result;
      }
    }
    return result;
  }
  
  function executeLesson(lesson) {
    lesson.compilationdiv.empty();
    lesson.testcasesdiv.empty();
    try {
      var userFunction = compile(lesson.editor.getValue(), lesson.inputs);
    } catch (err) {
      lesson.compilationdiv.append($('<pre>').text("Compilation failed: " + err));
      return;
    }

    _globalLanguageLevel = lesson.maxLanguageLevel;
    _globalAllowed = lesson.allowedSet;
    
    var testResults = runTests(userFunction, lesson.compiledSolution, lesson.inputs);

    var tableheader = $('<tr>');
    tableheader.append($('<th>').text("Test"));
    for (var input of lesson.inputs) {
      tableheader.append($('<th>').text(input));
    }
    tableheader.append($('<th>').text("Return value"));
    tableheader.append($('<th>').text("Expected"));
    tableheader.append($('<th>').text("Error"));

    var tablerows = $('<tbody>');
    var passed = true;
    var num = 0;
    for (var testCase of testResults) {
      var tr = $('<tr>');
      tr.append($('<td>').text(++num));
      for (var inputValue of testCase.inputs) {
        tr.append($('<td>').text(inputValue.toString()));
      }
      tr.append($('<td>').text(testCase.actual));
      tr.append($('<td>').text(testCase.expected));
      tr.append($('<td>').text(testCase.error));
      if (testCase.failed) {
        tr.addClass("failed");
      } else {
        tr.addClass("passed");
      }
      tablerows.append(tr);
    }

    var table = $('<table>');
    table
      .append($('<thead>').append(tableheader))
      .append(tablerows);
    lesson.testcasesdiv.append(table);
  }
  
  function setupLesson(lesson) {
    var lessondiv = $('<div>', {class: 'lesson'});

    lessondiv.append($('<h3>').text(lesson.title))
    lessondiv.append($('<p>').text(lesson.text))
    
    if (lesson.allowed) {
      lesson.allowedSet = new Set(lesson.allowed)
      lessondiv.append($('<p>').text("Allowed methods: " + lesson.allowed.join(", ")));
    }
    
    try {
      lesson.compiledSolution = compile(lesson.solution, lesson.inputs);
    } catch (err) {
      lessondiv.append($('<p>').text("Broken solution: " + solution + ", err: " + err));
    }
    
    var editordiv = $('<div>', {class: 'editor'});
    var editor = ace.edit(editordiv.get(0));
    editor.setTheme('ace/theme/monokai');
    editor.session.setMode('ace/mode/java');
    editor.setValue(lesson.code);
    lesson.editor = editor;
    
    var parameterList = lesson.inputs.join(', ');
    lessondiv.append(editordiv);

    lesson.compilationdiv = $('<div>', {class: 'compilation'});
    lesson.testcasesdiv = $('<div>', {class: 'testcases'});

    lessondiv.append(
      $('<button/>', {
          text: 'Run',
          click: () => executeLesson(lesson)
          }
      )
    );
    lessondiv.append(lesson.compilationdiv);
    lessondiv.append(lesson.testcasesdiv);

    $("#lessons").append(lessondiv);
    executeLesson(lesson);
  }

  function setupLessons() {
    for (lesson of lessons) {
      setupLesson(lesson);
    }
  }

  var lessons = [
    {
      title: "Simple transform",
      text: `Return a new future that adds a "!" to the input value`,
      inputs: [
        "input"
      ],
      code: `return input.thenApply(v -> v);`,
      solution: `return input.thenApply(v -> v + "!");`,
      allowed: ["thenApply"],
      maxLanguageLevel: 12,
    },
    {
      title: "Exception handling",
      text: `Now it's time to handle exceptions!
             Your code should do the same thing as before, but if the input future
             has an exception, your result future should convert the error string
             to "Error: " + exception`,
      inputs: [
        "input"
      ],
      code: `return input.thenApply(v -> v);`,
      solution: `
return input
  .thenApply(v -> v + "!")
  .exceptionally(e -> "Error: " + e.getMessage());`,
      allowed: ["thenApply", "exceptionally"],
      maxLanguageLevel: 12,
    },
    {
      title: "Combining futures",
      text: `Now we are going to get two futures as input. Your job is to return a future that is the concatenation of the values. You are only allowed to use thenCombine`,
      inputs: [
        "first", "second"
      ],
      code: `return null`,
      solution: `
return first.thenCombine(second, (a,b)->a+b);`,
      allowed: ["thenCombine"],
      maxLanguageLevel: 12,
    },
    {
      title: "Combining futures: part 2",
      text: `Same as previous, but now you have to solve it only using thenCompose and thenApply`,
      inputs: [
        "first", "second"
      ],
      code: `return null`,
      solution: `
return first.thenCompose(a -> second.thenApply(b -> a+b));`,
      allowed: ["thenCompose", "thenApply"],
      maxLanguageLevel: 12,
    },
    {
      title: "Combining multiple futures",
      text: `Now we are going to get three futures as input. Your job is to return a future that is the concatenation of the values.`,
      inputs: [
        "first", "second", "third"
      ],
      code: `return null`,
      solution: `
return first.thenCompose(a -> second.thenCompose(b -> third.thenApply(c -> a + b + c)));`,
      allowed: ["thenCompose", "thenApply"],
      maxLanguageLevel: 12,
    },
    {
      title: "Combining multiple futures: part 2",
      text: `Same as before, but now you have to use thenCombine and produce intermediate values`,
      inputs: [
        "first", "second", "third"
      ],
      code: `return null`,
      solution: `return first.thenCombine(second, (a,b)->a+b).thenCombine(third, (a,b)->a+b)`,
      allowed: ["thenCombine"],
      maxLanguageLevel: 12,
    },
    {
      title: "Retry on exceptions",
      text: `Now we are going to simulate a retry on exception. To simplify things, the retry logic is represented by the future called retry.`,
      inputs: [
        "input", "retry"
      ],
      code: `// Hint: look in the Java 12 futures API
return null`,
      solution: `
return input.exceptionallyCompose(exc -> retry);`,
      allowed: ["exceptionallyCompose"],
      maxLanguageLevel: 12,
    },
    {
      title: "Retry on exceptions: part 2",
      text: `Same as the previous lesson, but now you are not allowed to use methods defined in Java 12+.`,
      inputs: [
        "input", "retry"
      ],
      code: `// Hint: Can you first transform value into a nested future and unwrap it in the end?
return null`,
      solution: `
return input.thenApply(v -> CompletableFuture.completedFuture(v))
  .exceptionally(exc -> retry)
  .thenCompose(f -> f);`,
      allowed: ["thenApply", "exceptionally", "thenCompose"],
      maxLanguageLevel: 11,
    },
  ];

  _globalLanguageLevel = 12;
  setupLessons();
</script>
</body>
</html>
